#!/bin/bash
~/dev/uSDLC/uSDLC2/go gwt project=~/dev/AFP/FrenzyServer document=Design sections=.*/Data_Collection/Command.*
#~/dev/uSDLC/uSDLC2/go gwt project=~/dev/AFP/FrenzyServer document=Design sections=.*/Data_Collection/.*